# Generated by Django 4.0 on 2025-11-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proclean', '0002_carouselimage_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'verbose_name': 'CarouselImage', 'verbose_name_plural': 'CarouselImages'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
