# Generated by Django 4.0 on 2025-11-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proclean', '0003_alter_carouselimage_options_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
