# Generated by Django 4.0 on 2025-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proclean', '0004_alter_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ImageService',
                'verbose_name_plural': 'ImageServices',
            },
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
