# Generated by Django 4.0 on 2025-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proclean', '0005_imageservice_alter_carouselimage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('regular', 'Nettoyage Régulier'), ('deep', 'Nettoyage en Profondeur'), ('move', 'Nettoyage Déménagement'), ('airbnb', 'Nettoyage Airbnb'), ('carpet', 'Nettoyage de Tapis'), ('commercial', 'Nettoyage Commercial')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('button_text', models.CharField(default='En savoir plus', max_length=50)),
            ],
            options={
                'verbose_name': 'Carte de Service',
                'verbose_name_plural': 'Cartes de Services',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ImageService',
        ),
    ]
