# Generated by Django 6.0 on 2025-12-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proclean', '0008_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom *')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom *')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail *')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone *')),
                ('region', models.CharField(choices=[('montreal_laval', 'Montréal / Laval'), ('gatineau_ottawa', 'Gatineau / Ottawa'), ('quebec', 'Québec'), ('joliette_lanaudiere', 'Joliette / Lanaudière'), ('valdor_abitibi', 'Val-d’Or / Abitibi'), ('cotenord_saguenay', 'Côte-Nord / Saguenay'), ('autre', 'Autre')], max_length=50, verbose_name='Région où vous souhaitez travailler *')),
                ('region_autre', models.TextField(blank=True, null=True, verbose_name='Autre région (préciser)')),
                ('disponibilites', models.JSONField(default=list, verbose_name='Disponibilités *')),
                ('experience_menage', models.BooleanField(default=False, verbose_name="Avez-vous de l'expérience en entretien ménager ? *")),
                ('vehicule', models.BooleanField(default=False, verbose_name='Possédez-vous un véhicule ou moyen de transport fiable ? *')),
                ('cv', models.FileField(help_text='Formats acceptés: PDF, DOC, DOCX (max 5MB)', upload_to='cv_applications/%Y/%m/%d/', verbose_name='CV *')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message additionnel')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('consentement', models.BooleanField(default=False, verbose_name="J'accepte le traitement de mes données personnelles")),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
