# Generated by Django 6.0 on 2025-12-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proclean', '0010_alter_service_options_service_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCard',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
    ]
