# Generated by Django 6.0 on 2025-12-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proclean', '0011_delete_servicecard_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecrutementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('disponibilite', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='recrutement/cv/')),
                ('message', models.TextField(blank=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
    ]
