# Generated by Django 6.0 on 2025-12-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proclean', '0012_recrutementmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecrutementMessage',
        ),
    ]
